version: 0.2

env:
  variables:
    AWS_REGION: "ap-northeast-1"
#    key: "value"

phases:
  install:
    commands:
      # install required binary
      #- "yum install -y curl"
  pre_build:
    commands:
      - export AWS_RAW_CRED=$(curl --silent http://169.254.170.2:80$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI)
      - export AWS_ACCESS_KEY_ID=$(echo $AWS_RAW_CRED | jq -r '.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo $AWS_RAW_CRED | jq -r '.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo $AWS_RAW_CRED | jq -r '.Token')
      - export AWS_DEFAULT_REGION=$AWS_REGION

  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - chmod +x ./check_ebs_snapshot_fs/check_ebs_snapshot_fs.sh
      - chmod +x ./check_ebs_snapshot_fs/launch_instance.sh
      - cd check_ebs_snapshot_fs
      - ./launch_instance.sh

  post_build:
    commands:
      - echo "action completed on `date`"

artifacts:
  files:
    - '**/*'
