version: 0.2

env:
  variables:
    AWS_REGION: "ap-northeast-1"
#    key: "value"

phases:
  install:
    commands:
      # install required binary
      #- "yum install -y curl"
  pre_build:
    commands:
      - aws sts get-caller-identity
  build:
    commands:
      - credentials=$(aws sts assume-role --role-arn ${ASSUME_ROLE_ARN} --role-session-name "RoleSessionFromCodeBuild" | jq .Credentials)
      - export AWS_ACCESS_KEY_ID=$(echo ${credentials} | jq -r .AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo ${credentials} | jq -r .SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo ${credentials} | jq -r .SessionToken)
      - aws sts get-caller-identity
      - cd "$CODEBUILD_SRC_DIR"
      - chmod +x ./check_ebs_snapshot_fs/check_ebs_snapshot_fs.sh
      - chmod +x ./check_ebs_snapshot_fs/launch_instance.sh
      - ./check_ebs_snapshot_fs/launch_instance.sh

  post_build:
    commands:
      - echo "action completed on `date`"

artifacts:
  files:
    - '**/*'
